spring.application.name=mit-java-qualifier
spring.main.web-application-type=none

qualifier.name=${QUALIFIER_NAME:}
qualifier.reg-no=${QUALIFIER_REG_NO:}
qualifier.email=${QUALIFIER_EMAIL:}
qualifier.generate-webhook-url=${QUALIFIER_GENERATE_WEBHOOK_URL:https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA}
qualifier.authorization-prefix=${QUALIFIER_AUTH_PREFIX:}
qualifier.submit-on-startup=${QUALIFIER_SUBMIT_ON_STARTUP:false}
qualifier.fail-on-missing-query=${QUALIFIER_FAIL_ON_MISSING_QUERY:true}

qualifier.odd-final-query=${QUALIFIER_ODD_FINAL_QUERY:SELECT p.amount AS SALARY, CONCAT(e.first_name, ' ', e.last_name) AS NAME, TIMESTAMPDIFF(YEAR, e.dob, p.payment_time) AS AGE, d.department_name AS DEPARTMENT_NAME FROM payments p JOIN employee e ON p.emp_id = e.emp_id JOIN department d ON e.department = d.department_id WHERE DAY(p.payment_time) <> 1 AND p.amount = ( SELECT MAX(amount) FROM payments WHERE DAY(payment_time) <> 1 );}
qualifier.even-final-query=${QUALIFIER_EVEN_FINAL_QUERY:SELECT p.amount AS SALARY, CONCAT(e.first_name, ' ', e.last_name) AS NAME, TIMESTAMPDIFF(YEAR, e.dob, p.payment_time) AS AGE, d.department_name AS DEPARTMENT_NAME FROM payments p JOIN employee e ON p.emp_id = e.emp_id JOIN department d ON e.department = d.department_id WHERE DAY(p.payment_time) <> 1 AND p.amount = ( SELECT MAX(amount) FROM payments WHERE DAY(payment_time) <> 1 );}
